spec:
  inputs:
    image_name:
      description: "Docker image name"
      default: ""
    dockerfile:
      description: "Dockerfile name"
      default: Dockerfile
    context:
      description: "Docker build context"
      default: '.'
---

include:
  - component: $CI_SERVER_FQDN/components/build/buildkit@1
    inputs:
      image_name: $[[ inputs.image_name ]]
      dockerfile_name: $[[ inputs.dockerfile ]]
      context: $[[ inputs.context ]]
      runner_tags: ["ops-docker"]
      registry_type: gitlab_cr
      image_tag: $IMAGE_TAG
      pre_script:
        - cd $[[ inputs.image_name ]]
      rules_config:
        - if: $CI_PIPELINE_SOURCE == "web"
          when: manual
        - if: ($CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == $CI_DEFAULT_BRANCH) || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
          changes:
            - "$[[ inputs.image_name ]]/**/*"
          when: manual 
        - if: $CI_COMMIT_TAG
          variables:
            IMAGE_TAG: $CI_COMMIT_TAG
          when: manual
